### ISSUE TITLE
not working on a macosx 

### ISSUE THREAD

**Issue by robertgarrigos** [Evidlo/remarkable_mouse#10]
Not working on my Mac:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/remouse", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 165, in main
    read_tablet(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 106, in read_tablet
    monitor = get_monitors()[args.monitor]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 412, in get_monitors
    enumerator = _ENUMERATORS[name] if name else _get_enumerator()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 407, in _get_enumerator
    raise NotImplementedError('This environment is not supported.')
NotImplementedError: This environment is not supported.
```

**Comment by Evidlo** [comment]
https://github.com/Evidlo/remarkable_mouse/pull/8

**Comment by karenerobinson** [comment]
My traceback on a mac running OS 10.14.6, bash 3.2.57(1)-release, python 2.7.15

```
Traceback (most recent call last):
  File "/Users/karenerobinson/anaconda2/bin/remouse", line 6, in <module>
    from remarkable_mouse.remarkable_mouse import main
  File "/Users/karenerobinson/anaconda2/lib/python2.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 12, in <module>
    from screeninfo import get_monitors
  File "/Users/karenerobinson/anaconda2/lib/python2.7/site-packages/screeninfo/__init__.py", line 1, in <module>
    from .common import Enumerator, Monitor
  File "/Users/karenerobinson/anaconda2/lib/python2.7/site-packages/screeninfo/common.py", line 10
    x: int
     ^
SyntaxError: invalid syntax
```

yes i know that python 2 is deprecated as of a couple of weeks ago, but surely that's not my issue (?)

**Comment by Evidlo** [comment]
@karenerobinson The `screeninfo` lib uses typehints, which means that the minimum python version is 3.5.  I'll make a note in the readme.

**Comment by terencezl** [comment]
I was able to use #8's fix to get the proper `Monitor` class but was not able to make the mouse move on latest Catalina. I tried the `sudo` trick per @PalmaITEM's suggestion according to https://pynput.readthedocs.io/en/latest/limitations.html, but to no avail. the guide clarified that it was only for keyboard input, not for mouse or trackpad anyway. Any help?

**Comment by Evidlo** [comment]
Moving discussion to https://github.com/Evidlo/remarkable_mouse/issues/39, which is possibly fixed now.
