### ISSUE TITLE
Segmentation fault (cored dumped)

### ISSUE THREAD

**Issue by vchryssos** [Evidlo/remarkable_mouse#11]
OS: Ubuntu 18.04 LTS
python version: 2.7.15+
python3 version: 3.6.8

When I try to install I get the following error:
<pre>
Successfully built screeninfo dataclasses
Installing collected packages: six, enum34, python-xlib, pynput, dataclasses, screeninfo, pycparser, cffi, pynacl, bcrypt, asn1crypto, ipaddress, cryptography, paramiko, remarkable-mouse
Successfully installed asn1crypto-1.1.0 bcrypt-3.1.7 cffi-1.12.3 cryptography-2.7 dataclasses-0.6 enum34-1.1.6 ipaddress-1.0.22 paramiko-2.6.0 pycparser-2.19 pynacl-1.3.0 pynput-1.4.4 python-xlib-0.25 remarkable-mouse-4.1 screeninfo-0.4.1 six-1.12.0
Segmentation fault (core dumped)
</pre>

Then _remouse_ produces the following error:
<pre>
 Traceback (most recent call last):
  File "/home/USER/.local/bin/remouse", line 7, in <module>
    from remarkable_mouse.remarkable_mouse import main
  File "/home/USER/.local/lib/python2.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 12, in <module>
    from screeninfo import get_monitors
  File "/home/USER/.local/lib/python2.7/site-packages/screeninfo/__init__.py", line 1, in <module>
    from .common import Enumerator, Monitor
  File "/home/USER/.local/lib/python2.7/site-packages/screeninfo/common.py", line 10
    x: int
     ^
SyntaxError: invalid syntax
</pre>

**Comment by Evidlo** [comment]
Use pip3.  Python 2 is not supported.

**Comment by vchryssos** [comment]
Yes, it works fine with pip3.
Thank you!
