### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by flucoe** [Evidlo/remarkable_mouse#19]
When I try to use remouse, I get an error saying `Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer`

The full output reads:
```
(base) fernando@pop-os:~$ remouse 
Password for '10.11.99.1': 
Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

Traceback (most recent call last):
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fernando/anaconda3/bin/remouse", line 10, in <module>
    sys.exit(main())
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 81, in main
    remote_device = open_remote_device(args)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 58, in open_remote_device
    look_for_keys=False
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/home/fernando/anaconda3/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
```
Any ideas what is going on? Thanks.

**Comment by Evidlo** [comment]
Can you ssh into the device normally without errors?

**Comment by flucoe** [comment]
Should have checked that before, sorry. No. I get `kex_exchange_identification: read: Connection reset by peer` back

**Comment by flucoe** [comment]
I don't know if I should open a new issue or continue with this one. I'm now able to ssh into the device with no problems but remouse simply gets stuck after I enter the password. Adding --debug  results in the following:

```
$ remouse --debug
Password for '10.11.99.1': 
Debugging enabled...
Chose monitor: Monitor(x=0, y=0, width=1920, height=1080, width_mm=344, height_mm=194, name='eDP-1')
```
but nothing happens after this.

**Comment by flucoe** [comment]
Sorry, I just figured it out. Please disregard the previous message.

**Comment by eagboola** [comment]
hey, @flucoe.  I seem to be stuck in the same spot: remouse gets stuck after I enter the password.

C:\Users\Ekerin>remouse
Password for '10.11.99.1':
connected to 10.11.99.1

That's as far as I get and nothing happens. No response. 
What did you do or check that made it work?

**Comment by flucoe** [comment]
@eagboola In my case it was "user error". It was not really getting stuck as if I draw on the remarkable, the "coordinates" would change on the terminal but the monitor was incorrectly identified.
