### ISSUE TITLE
Connects to ReMarkable2, but doesn't "do" anything

### ISSUE THREAD

**Issue by raffraffraff** [Evidlo/remarkable_mouse#56]
OS: Ubuntu 20.04
Python 3.8

Output isn't helpful:
```
$ remouse --address 192.168.0.151
connected to 192.168.0.151
```

Debug output isn't helpful either:
```
$ remouse --address 192.168.0.151 --debug
connected to 192.168.0.151
Debugging enabled...
Chose monitor: Monitor(x=0, y=0, width=1600, height=900, width_mm=344, height_mm=194, name='eDP-1')
```

If I monitor journalctl output on the ReMarkable2, I can see that it makes an attempt to ssh and succeeds (using a key). But it doesn't seem to "do" anything. I can't see any new process running on the ReMarkable2 after running remouse.

**Comment by fancypantalons** [comment]
This is a duplicate of #52.  Check out that thread for a workaround in the meantime (confirmed over here).

**Comment by ebauch** [comment]
On Mac OS, installing the rm2 branch worked for me via 

```
python -m pip install git+https://github.com/Evidlo/remarkable_mouse.git#rm2
```

**Comment by twitwi** [comment]
NB: you might need a `@` instead of `#` to install from a specific branch (see https://pip.pypa.io/en/stable/topics/vcs-support/ )

**Comment by cesss** [comment]
For people who see "nothing" on MacOS, I was experiencing the same, and fixed it by adding permission to Terminal to control the computer on the Security and Privacy category in MacOS System Settings.

**Comment by Evidlo** [comment]
Is this still the case for anyone using Ubuntu?  The rm2 branch was merged in master long ago.

**Comment by Hellunteur** [comment]
Hello, On Arch here, Manjaro to be precise, and i've got a similar issue. I've dug as much as I could and this issue is the most simmilar. 

I get this error where screen selector doesnt' seem to work. I've checked that my Python and my config is up to date. Manually re-installed all the python libraries needed. Running out of ideas any help would be great as I believe this to be a great project. 


```python
    ~/Downloads  remouse --debug                                                               ✔ 
Password for '10.11.99.1': 
connected to 10.11.99.1
Debugging enabled...
Chose monitor: Monitor(x=0, y=0, width=1920, height=1200, width_mm=302, height_mm=189, name='eDP-1', is_primary=True)
1
1
^C%                                                                                                        ~/Downloads  remouse --debug --monitor 1                                           ✔  14s  
Password for '10.11.99.1': 
connected to 10.11.99.1
Debugging enabled...
Traceback (most recent call last):
  File "/usr/bin/remouse", line 33, in <module>
    sys.exit(load_entry_point('remarkable-mouse==5.2.1', 'console_scripts', 'remouse')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/remarkable_mouse/remarkable_mouse.py", line 119, in main
    read_tablet(args, remote_device)
  File "/usr/lib/python3.12/site-packages/remarkable_mouse/pynput.py", line 70, in read_tablet
    monitor = get_monitors()[args.monitor]
              ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
    ~/Downloads                                                                              1 ✘ 




```

**Comment by Evidlo** [comment]
Since I didn't hear anything I'm assuming this is fixed.
