### ISSUE TITLE
doesn't run ... syntaxe error 

### ISSUE THREAD

**Issue by andrelec1** [Evidlo/remarkable_mouse#60]
```
╭─andrelec1@ESD1 ~ 
╰─$ remouse
Traceback (most recent call last):
  File "/home/andrelec1/.local/bin/remouse", line 5, in <module>
    from remarkable_mouse.remarkable_mouse import main
  File "/home/andrelec1/.local/lib/python3.8/site-packages/remarkable_mouse/remarkable_mouse.py", line 12, in <module>
    import paramiko
  File "/home/andrelec1/.local/lib/python3.8/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/andrelec1/.local/lib/python3.8/site-packages/paramiko/transport.py", line 66, in <module>
    from paramiko.sftp_client import SFTPClient
  File "/home/andrelec1/.local/lib/python3.8/site-packages/paramiko/sftp_client.py", line 41, in <module>
    from paramiko.sftp_file import SFTPFile
  File "/home/andrelec1/.local/lib/python3.8/site-packages/paramiko/sftp_file.py", line 66
    self._close(async=True)
                ^
SyntaxError: invalid syntax

```

what i can do  ?

**Comment by Julien00859** [comment]
Hello there, the issue have been brought to another community forum where we made him upgrade paramiko to the latest version. Oddly enough it was not the latest version that was installed on his system.

    $ python3 -m pip install --upgrade paramiko

Thanks to this issue, I have the opportunity to spread the word about `setup.cfg`, `pypackage.toml` and `python3 -m build` which are newer (and imho more robust) ways to package python packages. A quick glance at the way your package is currently packaged it is possible you'll have an issue with the `__version__` variable, you can use the `attr:` directive to retrieve it, see [here](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html?highlight=metadata#configuring-setup-using-setup-cfg-files).

https://packaging.python.org/tutorials/packaging-projects/
