### ISSUE TITLE
Crash after connection

### ISSUE THREAD

**Issue by Xaver106** [Evidlo/remarkable_mouse#71]
I'm on Windows 11 with a remarkable 2

Console output:
```
>remouse
Password for '10.11.99.1':
Connected to 10.11.99.1
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\Scripts\remouse.exe\__main__.py", line 7, in <module>
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\remarkable_mouse\remarkable_mouse.py", line 148, in main
    from remarkable_mouse.pynput import read_tablet
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\remarkable_mouse\pynput.py", line 4, in <module>
    import libevdev
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\__init__.py", line 23, in <module>
    from .device import Device, InputAbsInfo
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\device.py", line 29, in <module>
    from .event import InputEvent
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\event.py", line 23, in <module>
    from .const import EventType, EventCode
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\const.py", line 427, in <module>
    _load_consts()
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\const.py", line 352, in _load_consts
    Libevdev()  # classmethods, need to make sure it's loaded at once
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\_clib.py", line 395, in __init__
    super(Libevdev, self).__init__()
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\_clib.py", line 76, in __init__
    self._load()
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\_clib.py", line 83, in _load
    cls._lib = cls._cdll()
  File "C:\Users\xaver\AppData\Roaming\Python\Python310\site-packages\libevdev\_clib.py", line 123, in _cdll
    return ctypes.CDLL("libevdev.so.2", use_errno=True)
  File "C:\Program Files\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libevdev.so.2' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by Xaver106** [comment]
It looked to me like some issue with python, but I reinstalled it already and no change

**Comment by Evidlo** [comment]
This is a known issue.  I would try an older version for the time being.  Also Windows performance is generally not that good right now.

    pip install remarkable_mouse==6.0.0

**Comment by Xaver106** [comment]
ok, thanks for letting me know
