### ISSUE TITLE
remouse: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by Jayy001** [Evidlo/remarkable_mouse#78]
```
❯❯ remouse --debug                                                                                  ?1
Debugging enabled...
Connecting to input '10.11.99.1'
Traceback (most recent call last):
  File "/home/jacob/.asdf/installs/python/3.7.10/bin/remouse", line 8, in <module>
    sys.exit(main())
  File "/home/jacob/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 158, in main
    password=args.password,
  File "/home/jacob/.asdf/installs/python/3.7.10/lib/python3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 73, in open_rm_inputs
    elif 'identityfile' in config_entry and len(config_entry['identityfile']) > 0:
TypeError: argument of type 'NoneType' is not iterable
```

Installed on `python.3.7.10`, arch / endavour OS via`pip instsall remarkable-mouse`. Modifications on tablet include `toltec` and `LAMY eraser hack` (`ddvk not installed`)

Also ran with `remouse --password <pass here>` which gives the same issue

**Comment by Evidlo** [comment]
Should be fixed with 7.1.1
