### ISSUE TITLE
remouse won't connect on linux mint

### ISSUE THREAD

**Issue by pcklink** [Evidlo/remarkable_mouse#87]
While everything works great on my macbook, I can't seem to get it running on my Linuc Mint desktop machine. I can ssh into my Remarkable 2 just fine, but the remouse command throws an SSHException I don't understand. I tried setting up passwordless access but that doesn't work either. Any ideas on how to fix this?

```
Exception (client): key cannot be used for signing
Traceback (most recent call last):
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/transport.py", line 2220, in run
    handler(m)
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/auth_handler.py", line 404, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob, algorithm)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/agent.py", line 496, in sign_ssh_data
    raise SSHException("key cannot be used for signing")
paramiko.ssh_exception.SSHException: key cannot be used for signing

Traceback (most recent call last):
  File "/home/chris/anaconda3/bin/remouse", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chris/anaconda3/lib/python3.11/site-packages/remarkable_mouse/remarkable_mouse.py", line 155, in main
    rm_inputs = open_rm_inputs(
                ^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/lib/python3.11/site-packages/remarkable_mouse/remarkable_mouse.py", line 90, in open_rm_inputs
    client.connect(
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
  File "/home/chris/anaconda3/lib/python3.11/site-packages/paramiko/transport.py", line 1592, in auth_password
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

**Comment by pcklink** [comment]
Solved it by softlinking the authorized_keys from the dropbear folder to the ssh folder on the remarkable:
`ln -s /etc/dropbear/authorized_keys ~/.ssh/`
